#!/bin/sh

./bootstrap.sh "$@"

cat <<EOF > "Makefile"
LIB_TARGETS = --with-chrono --with-system --with-random --with-filesystem --with-thread
all:
	./b2 -j `nproc --ignore=1` \$(LIB_TARGETS)
install:
	./b2 install \$(LIB_TARGETS)
EOF
